### ISSUE TITLE
page xiii footnote link doesn't work in print

### ISSUE THREAD

**Issue by gfixler** [hmemcpy/milewski-ctfp-pdf#101]
I've noticed this a few times now when checking in the project; I thought I'd report it.

Page xiii mentions at the bottom that the reader can watch this online, which is a link, but when printed, it's just going to be a very teasing message telling you what you can do, but now how. Maybe there's a way to add a nice, shortened URL along with that note, for print copies?

**Comment by hmemcpy** [comment]
That's a good idea! Thanks, I'll gfix (😂) the link

**Comment by hmemcpy** [comment]
But now I wonder, do I place a short url (goo.gl, bit.ly, which may die one day), or an untypable youtube playlist url?
Or google search keywords?

**Comment by hmemcpy** [comment]
How's this?
![image](https://user-images.githubusercontent.com/601206/34775822-2d66e76e-f61d-11e7-914e-19198a283a3e.png)
