### ISSUE TITLE
Gaps on Page 132

### ISSUE THREAD

**Issue by fosskers** [hmemcpy/milewski-ctfp-pdf#106]
There are some strange paragraph gaps on page 132, but the raw Tex doesn't suggest there should be anything there: https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/1.8/Functoriality.tex#L544

![2018-01-22-115246_1918x1078_scrot](https://user-images.githubusercontent.com/229679/35241318-f0557f5a-ff6a-11e7-8cc1-7e336d26f3cb.png)

Is this maybe some fluke of LaTeX's typesetting?

**Comment by hmemcpy** [comment]
Hmm, you're right! I suspect this is a combination of having the image on the next page (133) and some other package, perhaps nowindow?

Thanks for reporting, I'll try playing with it, see if it can be improved...

**Comment by hmemcpy** [comment]
![image](https://user-images.githubusercontent.com/601206/35244232-2ad7bd20-ffc8-11e7-8ec8-7db1352619b5.png)

Much better :)
