### ISSUE TITLE
"The font "Libertinus Math" cannot be found." - macOS High Sierra

### ISSUE THREAD

**Issue by timmyjose** [hmemcpy/milewski-ctfp-pdf#108]
Following the instructions in the README, I installed `mactex` using homebrew. I also downloaded the two mentioned fonts from the provided links. However, building on a macOS High Sierra machine gave the following error:

 >(/usr/local/texlive/2017/texmf-dist/tex/latex/unicode-math/unicode-math-table.t
 >ex)))kpathsea:make_tex: Invalid fontname `Libertinus Math/OT', contains ' '
  
> !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
> !
> ! fontspec error: "font-not-found"
> !
> ! The font "Libertinus Math" cannot be found.
> !
> ! See the fontspec documentation for further information.
> !
> ! For immediate help type H <return>.
> !...............................................
> 
> l.31 \setmathfont{Libertinus Math}

My macOS version:

`$ uname -a
Darwin ******.local 17.2.0 Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64 x86_64
`
After I installed the specified font from [https://fontlibrary.org/en/font/libertinus-math](https://fontlibrary.org/en/font/libertinus-math), the installation went through fine. 

Just for completion, my `mactex` version is:

`$ brew cask info mactex
mactex: 20170524
https://www.tug.org/mactex/
/usr/local/Caskroom/mactex/20170524 (2.9GB)
From: https://github.com/caskroom/homebrew-cask/blob/master/Casks/mactex.rb
==> Name
MacTeX
==> Artifacts
mactex-20170524.pkg (Pkg)`

**Comment by hmemcpy** [comment]
Oh! You're right, I changed the font and forgot to update the readme... Thanks, I'll handle it later, unless you want to send a PR :)

**Comment by timmyjose** [comment]
Wow, thanks for the quick response! I'd be glad to make the small changes and submit a PR. :-)

**Comment by timmyjose** [comment]
Done!
