### ISSUE TITLE
Breaks with "\lbrace already defined"

### ISSUE THREAD

**Issue by plumdeq** [hmemcpy/milewski-ctfp-pdf#111]
Hi,

I'm unable to compile from source. Here is the log of running the `make`

``` 
! LaTeX Error: Command `\lbrace' already defined.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.54 ...open}{parenthesis}{"7B}{largesymbols}{"08}
```

**Comment by hmemcpy** [comment]
Sorry for the lack of response on this issue. I think it may have been caused by the TexLive version you had installed. I made some tweaks to allow it to compile under both 2017 and 2018.
I'm closing this, as there's now also a CI server that builds the book.
