### ISSUE TITLE
Suggestion: use nix to describe build

### ISSUE THREAD

**Issue by markus1189** [hmemcpy/milewski-ctfp-pdf#125]
I saw some issues with people failing to locally compile the book.

I hacked up a nix shell environment here: https://gist.github.com/markus1189/713bbd6375fbc10d1ccc8c838fda1598

We could use that so that:

* people can use the nix package manager (https://nixos.org/nix/manual/) to build the pdf locally without worrying about missing dependencies and the general latex packagemanagement.
* the travis build can re-use the `shell.nix` file and would only contain a single line for the build script
* we could probably also build a docker image from the `shell.nix` that provides the same environment

What do you think?

**Comment by hmemcpy** [comment]
Oh wow!
(also, hi Markus, big fan of your talks in Scala conferences :))

I think this is great, I had a bit of bad luck setting up an linux image that would "just work". I'd be happy to accept it!
Unfortunately, I haven't made it around yet to playing with nix, do you think you could set up the CI build on travis/another CI server?

Thanks a lot! 👍

**Comment by markus1189** [comment]
On Sun, Jul 15, 2018 at 10:38 AM Igal Tabachnik <notifications@github.com>
wrote:

> Oh wow!
> (also, hi Markus, big fan of your talks in Scala conferences :))
>
​> Oh thanks! If you ever meet me on a conference, we should catch up :)​


> I think this is great, I had a bit of bad luck setting up an linux image
> that would "just work". I'd be happy to accept it!
> Unfortunately, I haven't made it around yet to playing with nix, do you
> think you could set up the CI build on travis/another CI server?
>
​> Sure: ​https://github.com/hmemcpy/milewski-ctfp-pdf/pull/126

**Comment by hmemcpy** [comment]
...and 6000 output lines later, it "just works!" This is amazing! https://travis-ci.org/hmemcpy/milewski-ctfp-pdf/builds/404079430
```
Output written on ctfp.pdf (519 pages).

Transcript written on ctfp.log.
=== TeX engine is 'XeTeX'
Latexmk: Index file 'ctfp.idx' was written
Latexmk: Log file says output to 'ctfp.pdf'
Latexmk: All targets (ctfp.pdf) are up-to-date
The command "nix-shell --pure shell.nix --command 'cd src; make'" exited with 0.

Skipping a deployment with the releases provider because this is not a tagged commit
Done. Your build exited with 0.
```

Thank you so much, Markus :) Your name goes to the acknowledgements section immediately!

**Comment by markus1189** [comment]
I know how you feel, this is one of my favourite things to do :heart: , because I can re-use the same environment locally and on travis, knowing that if it works locally it will work exactly like that on travis as well.

**Comment by hmemcpy** [comment]
​> Oh thanks! If you ever meet me on a conference, we should catch up :)​

Absolutely! I'm going to ScalaExchange in December, hopefully something else sooner :)

> because I can re-use the same environment locally and on travis

![image](https://user-images.githubusercontent.com/601206/42732278-2689859a-8827-11e8-9432-b254cf61279f.png)
