### ISSUE TITLE
E-book reader support

### ISSUE THREAD

**Issue by peteyycz** [hmemcpy/milewski-ctfp-pdf#129]
Is it possible to get the book in epub format?

**Comment by alejandrodnm** [comment]
👍

**Comment by alejandrodnm** [comment]
#46 
#100

**Comment by alejandrodnm** [comment]
There are two issues regarding that #46 and #100.

**Comment by hmemcpy** [comment]
Sorry for the lack of responses. I'm closing this as a duplicate of #46, which is still open. Hopefully I'll be able to look at it soon.
