### ISSUE TITLE
Cover for printing

### ISSUE THREAD

**Issue by hmemcpy** [hmemcpy/milewski-ctfp-pdf#133]
I am finally ready to set up a printed version of the book. I need a cover page (front and back) to use with the PDF.
I found the [bookcover](https://ctan.org/pkg/bookcover?lang=en) package which seems useful to do exactly what I need.

Any help (and some design sense) is appreciated!

Here are the specifications from the publisher website:
![image](https://user-images.githubusercontent.com/601206/43459308-cb443e08-94d5-11e8-915b-58865ac88ad9.png)
![image](https://user-images.githubusercontent.com/601206/43459325-d7aabb04-94d5-11e8-987f-3eb2b7deeac7.png)

**Comment by hmemcpy** [comment]
If it helps, here's an Adobe InDesign template for the exact cover (zipped). Do your best :)
[Category Theory for Programmers Cover.indd.zip](https://github.com/hmemcpy/milewski-ctfp-pdf/files/2247154/Category.Theory.for.Programmers.Cover.indd.zip)

**Comment by BartoszMilewski** [comment]
How do I open it? I don't have Adobe.

**Comment by hmemcpy** [comment]
@BartoszMilewski hmm, I downloaded the Adobe InDesign trial... you could do that.
In the meantime, I've started looking on [fiverr](https://www.fiverr.com/) for someone professional to design the cover :) I want it to look great!

Speaking of, could you provide a short text for the back cover? Something like "What is category theory", but in your words?
Thank you!

**Comment by hmemcpy** [comment]
This is the book cover I currently came up with! Feel free to send your artistic modifications :)
![cover](https://user-images.githubusercontent.com/601206/44384552-39fc2900-a525-11e8-9be8-c5bc2af7879a.png)

**Comment by BartoszMilewski** [comment]
Looks good! What printing service is it going to be available on?
--Bartosz

**Comment by hmemcpy** [comment]
I've been reading a whole bunch of posts, Lulu seems to have the best price/quality, so Lulu with possibly selling on Amazon as well... Looking into that

**Comment by mpoullet** [comment]
Is there a way to get notified when it's available?
