### ISSUE TITLE
Remove bg from the pictures?

### ISSUE THREAD

**Issue by Zelenya** [hmemcpy/milewski-ctfp-pdf#138]
Love the pictures in the book and how the look on the website. They seem less natural in the b/w pdf. What would you say about PR doing something like this?

![2](https://user-images.githubusercontent.com/11508062/44675268-4eae5480-aa30-11e8-8859-47f2f38d3bd3.png)

@BartoszMilewski @hmemcpy

**Comment by BartoszMilewski** [comment]
How much work would that be?

**Comment by Zelenya** [comment]
Not much, I'll be happy to do it if you think it looks better.

**Comment by hmemcpy** [comment]
Looks great!
Are you planning to do it for all images? Honestly, some watercolor ones may benefit from the original background. If you can, keep both versions of the images, then we can decide which looks better (perhaps conditionally in LaTeX)

**Comment by Zelenya** [comment]
Did somebody become addicted to LaTeX? :wink: Will do: all images + couple of options.

**Comment by hmemcpy** [comment]
This is now fixed! Thanks @Zelenya!
