### ISSUE TITLE
1. Declarative Programming

### ISSUE THREAD

**Issue by hmemcpy** [hmemcpy/milewski-ctfp-pdf#14]

**Comment by raol** [comment]
I'll take this one

**Comment by hmemcpy** [comment]
Awesome! Thank you!
I'm tweaking the LaTeX a bit, removing syntax highlighting (keeping everything in `{verbatim}` blocks. Also, I've switched to `\code` instead of '`\texttt`, and converting some of the `\emph` to `\newterm` (defined in preamble.tex), so that it is auto-indexed :)
Please see the first 5 documents from part 1 for hints.

Thanks again!

**Comment by hmemcpy** [comment]
Also removing an empty line between `\end{verbatim}` and the next paragraph will keep it unindented. So please try and fix that, e.g.:
```
\end{verbatim}
Unindented...

Next paragraph
```
