### ISSUE TITLE
Add 'note from the editor' to the book

### ISSUE THREAD

**Issue by hmemcpy** [hmemcpy/milewski-ctfp-pdf#147]
Explain code styles, and in case of other language editions, explain the differences when both code snippets are present.
(e.g. where it says "In Haskell...", it should read "in Haskell and <language>")

**Comment by hmemcpy** [comment]
Introduce a conditional option `\OPTscala` to include scala-specific text.
In the note from the editor, include the use of the Kind projector plugin when \OPTscala is defined.

**Comment by kubukoz** [comment]
I understand that this can be closed after https://github.com/hmemcpy/milewski-ctfp-pdf/commit/c920207e28bf7d32e7fa7476ef51ff735cdd1eff?
