### ISSUE TITLE
Preface: functional programming "composing" concurrency may require clarification

### ISSUE THREAD

**Issue by eulerfx** [hmemcpy/milewski-ctfp-pdf#149]
```
Functional programming is not only about composing functions
and algebraic data structures --- it makes concurrency composable ---
something that's virtually impossible with other programming paradigms.
```

It may be worth nothing that the Lambda calculus (CCCs) models of *sequential* computation. This is not to say that functional programming is limited to the lambda calculus. Take a look [here](https://golem.ph.utexas.edu/category/2011/04/higher_categories_for_concurre.html) which, by a reference to Robin Milner's Turing Award lecture, suggests that CCCs are not the right semantic framework for concurrency, but perhaps the more general symmetric monoidal categories are. This connection is explored in a few other places, some of which are:

- [Interaction Categories and the Foundations of
Typed Concurrent Programming](https://pdfs.semanticscholar.org/2cae/af7f3722ecbf5d830ce13b42572672c3da51.pdf) - defines a category Proc wherein product is composition.

- [Models of Concurrency](https://www.irif.fr/~mellies/mpri/mpri-ens/articles/winskel-nielsen-models-for-concurrency.pdf) - unifies several models of concurrency (event structures, Petri nets, trace languages, pi-calculus) using the language of Grothendieck fibrations.

- [Sheaf Semantics for Concurrent Interacting Objects](https://pdfs.semanticscholar.org/569a/8c66bac1e8b034b26c77494bbe1dd4e8c88e.pdf) - uses sheaf/topoi theory to provide semantics for concurrency.

- [Conflation Confers Concurrency](http://homepages.inf.ed.ac.uk/slindley/papers/conflate.pdf) - notes the connection of LL with session types, pi-calculus and compares to the relationship between intuitionistic logic and lambda calculus. More on this by Wadler.

- [The Topological Structure of Asynchronous
Computability](http://cs.brown.edu/people/mph/HerlihyS99/p858-herlihy.pdf) - provides a framework for and shows that consensus is non-terminating using homology.

More references on https://ncatlab.org/nlab/show/linear+logic. 

Overall, I think it is a slight exaggeration to say the FP "composes" concurrency since there is still a ways to go in even establishing an agreed-upon model of concurrency. The references above seem to hint at a deep relationship between concurrency, LL, and categorical models of quantum mechanics. With that said, programming concurrent systems using FP techniques is certainly advantageous.

**Comment by hmemcpy** [comment]
While I surely appreciate the time you took to write this comment, I'm afraid I can't be of much help here - Bartosz doesn't usually check this site, and I don't/can't influence the content of the book. You add this as a comment on Bartosz' blog (I know he checks them and responds).
I'm closing this for now.

**Comment by BartoszMilewski** [comment]
I do get notifications from github.

**Comment by hmemcpy** [comment]
Heh :) Glad you're watching!
