### ISSUE TITLE
Link to v1.0.0 does not work

### ISSUE THREAD

**Issue by jmgimeno** [hmemcpy/milewski-ctfp-pdf#151]
The link in the README to the version 1 pdf does not work and, in the releases page, there are no PDFs for the v1.0.0

**Comment by hmemcpy** [comment]
Heh, it was foolish of me to attempt a release from the train!
It's uploading, I'll close this issue when it's up... thanks for the heads up!

**Comment by hmemcpy** [comment]
Seems ok now!
