### ISSUE TITLE
Install github pygments style from nix

### ISSUE THREAD

**Issue by hmemcpy** [hmemcpy/milewski-ctfp-pdf#164]
This should run before trying to build the PDF.

Nix magicians, can you help? :)

https://pypi.org/project/pygments-style-github/

**Comment by lionello** [comment]
I can look into it. Assign to me?

**Comment by lionello** [comment]
@hmemcpy Do you happen to have the actual parameters that must be passed to `pygmentize`?

**Comment by hmemcpy** [comment]
This is now done!
