### ISSUE TITLE
Permission to print the book

### ISSUE THREAD

**Issue by oschrenk** [hmemcpy/milewski-ctfp-pdf#167]
This somewhat tangential (and maybe even redundant) but I wanted to print a copy of the book and my printer was asking for written permission of the author of the book. 

My understanding that this is implicit with the given CC by SA license as long as I keep everything intact and I print files taken from the releases.

Is my understanding correct that I am allowed to print the book?

**Comment by hmemcpy** [comment]
Yes, you can print your own copy!
This is what the CC license explicitly allows, even says so in the [FAQ](https://creativecommons.org/faq/#can-i-take-a-cc-licensed-work-and-use-it-in-a-different-format):

> **Can I take a CC-licensed work and use it in a different format?**
Yes. When any of the six CC licenses is applied to material, licensees are granted permission to use the material as the license allows, whatever the media or format chosen by the user when it is used or distributed further. This is true even in our NoDerivatives licenses. This is one of a very few default rules established in our licenses, to harmonize what may be different outcomes depending on where CC-licensed material is reused and what jurisdiction’s copyright law applies.
> 
> This means, for example, that even if a creator distributes a work in digital format, you have permission to print and share a hard copy of the same work.

Bartosz' original blog posts are licensed CC-BY-SA, as well as the PDF book.
For "legalese" of this grant, please see [Section 2, a. License grant, bullet 4](https://creativecommons.org/licenses/by-sa/4.0/legalcode)

Hope this helps!

**Comment by oschrenk** [comment]
It helped. Pointing out the FAQ and your voice convinced the printer.
