### ISSUE TITLE
Quotation mark in preface

### ISSUE THREAD

**Issue by adah1972** [hmemcpy/milewski-ctfp-pdf#171]
src/content/0.0/preface.tex has:

> or search "bartosz milewski category theory" on YouTube.

This is rendered into the typographically incorrect result:

> or search ”bartosz milewski category theory” on YouTube.

I suppose the following should be written according to the TeX convention:

> or search ``bartosz milewski category theory'' on YouTube.

**Comment by hmemcpy** [comment]
Thanks (sorry it took too long to respond!)
This is now fixed.
