### ISSUE TITLE
3.1 Component equations for unit and counit

### ISSUE THREAD

**Issue by aleksey-makarov** [hmemcpy/milewski-ctfp-pdf#202]
I believe the domains for `\varepsilon` and `R \varepsilon` in the component wise equations are wrong, and the equations 

\varepsilon_{L d} \circ L \eta_d = \id_{L d}
R \varepsilon_{c} \circ \eta_{R c} = \id_{R c}

should read as

\varepsilon_{L \circ R \circ L d} \circ L \eta_d = \id_{L d}
R \varepsilon_{L \circ R c} \circ \eta_{R c} = \id_{R c}

**Comment by BartoszMilewski** [comment]
It type checks:
L \eta_d :: L d \to L R L d. 
\varepsilon_c :: L R c \to c
\varepsilon_{L d} :: L R L d \to L d
the composition goes from L d to L d.

**Comment by aleksey-makarov** [comment]
Is this correct:  

\varepsilon_c :: L R c \to c

?  I believe this should be

\varepsilon_{L R c} :: L R c \to c

Few lines above you had to introduce c' for the same reason

**Comment by BartoszMilewski** [comment]
I know it's a little confusing. In fact I get confused about it every time. Here's the trick: Draw three categories instead of two: C, D, and C again. The arrow starts at c, R takes it right, and L takes it right again to the second C. Id takes c directly from the leftmost C to the rightmost one. Then you drop epsilon_c between them.

**Comment by aleksey-makarov** [comment]
As far as I understand the lower index of a component of a natural transformation denotes domain (but not codomain) of that component.  So component of natural transformation epsilon that goes from L R c to c is epsilon_{L R c} but not epsilon_c right?

**Comment by BartoszMilewski** [comment]
Think of a natural transformation between two functors F and G. Its component at c is a morphism alpha_c :: F c -> G c. Replace F with (L \circ R) and G with Id.

**Comment by aleksey-makarov** [comment]
Thank you very much.
