### ISSUE TITLE
Drawing commutative diagrams with TikZ

### ISSUE THREAD

**Issue by platipo** [hmemcpy/milewski-ctfp-pdf#214]
The images are quite nice but sometimes they feel kinda cheap. It would be nice if they could be redrawn with TikZ.
This would give a touch of class to a book that is already beautiful.

Example:
![scanned diagram](https://github.com/hmemcpy/milewski-ctfp-pdf/raw/master/src/content/3.15/images/spanmul.png)

Simple solution:
![TikZ-diagram-simple](https://user-images.githubusercontent.com/22260641/64782680-1c519580-d566-11e9-9fb1-69efd0115582.png)

```latex
\begin{tikzcd}[commutative diagrams/every, column sep=small, cells={nodes={inner color=blue!20!white,outer color=white}}]
    & & Arr\otimes Arr \arrow[dr] \arrow[dl] \arrow[d, phantom, "\vee", very near start,font=\Large] & & \\
    & Arr \arrow[dl, swap, "dom"] \arrow[dr, swap, "cod"] & & Arr \arrow[dl, swap, "dom"] \arrow[dr, swap, "cod"] & \\
    Ob & & Ob & & Ob \\
\end{tikzcd}
```

And a more complex one:
![TikZ-diagram-complex](https://user-images.githubusercontent.com/22260641/64782693-22e00d00-d566-11e9-8cd9-6429465a375e.png)

```latex
\begin{tikzpicture}[commutative diagrams/every, column sep=small, cells={nodes={inner color=blue!20!white,outer color=white}}]
    \def\colspace{1.2}
    \def\rowspace{1.5}
    \node[inner color=purple!50!blue!20!white,outer color=white] (P0) at (2*\rowspace, 2*\colspace) {$Arr\otimes Arr$};
    \node[inner color=purple!50!blue!20!white,outer color=white] (P1) at (1*\rowspace, 1*\colspace) {$Arr$};
    \node[inner color=purple!50!blue!20!white,outer color=white] (P2) at (3*\rowspace, 1*\colspace) {$Arr$};
    \node[inner color=blue!30!white,outer color=white] (P3) at (0*\rowspace, 0*\colspace) {$Ob$};
    \node[inner color=blue!30!white,outer color=white] (P4) at (2*\rowspace, 0*\colspace) {$Ob$};
    \node[inner color=blue!30!white,outer color=white] (P5) at (4*\rowspace, 0*\colspace) {$Ob$};
    \node (P0b) at (2*\rowspace, 1.7*\colspace) {\rotatebox[origin=c]{180}{ $\mathbf{\widehat{}}$}};

    \path[commutative diagrams/.cd,every arrow, every label]
        (P0) edge node {} (P1)
        (P0) edge node {} (P2)
        (P1) edge node[swap] {$dom$} (P3)
        (P1) edge node[swap] {$cod$} (P4)
        (P2) edge node[swap] {$dom$} (P4)
        (P2) edge node[swap] {$cod$} (P5)
\end{tikzpicture}
```

**Comment by platipo** [comment]
What could be done to improve the diagram? What is it missing from the original one?

**Comment by platipo** [comment]
Removed the colors this is how it appears in the book:

![TikZ-page](https://user-images.githubusercontent.com/22260641/64848300-2b415200-d611-11e9-8971-b0304030e430.png)

and this is the original:

![original-page](https://user-images.githubusercontent.com/22260641/64848375-588e0000-d611-11e9-8763-75eb92a45459.png)

**Comment by XVilka** [comment]
This way it looks more professional, indeed. But the point of highlighting the `Arr` is lost. Maybe use the bold font for this?

**Comment by platipo** [comment]
I tried some alternatives:
-  Coloured ![colored](https://user-images.githubusercontent.com/22260641/64857875-1b803880-d626-11e9-9257-6787e278a783.jpg)

- Various bold types (for clarity I added the bold style in gray)
![bold](https://user-images.githubusercontent.com/22260641/64857874-1b803880-d626-11e9-959c-83ccd93eb726.png)

- Both the previous solutions (bold styles order is preserved) ![bold-colored](https://user-images.githubusercontent.com/22260641/64857876-1b803880-d626-11e9-8fb2-5266691c4a20.jpg)

**Comment by BartoszMilewski** [comment]
I like the simplest one (no color, no bold) best. Go ahead and make the change.

**Comment by platipo** [comment]
Do you prefer to embed `\tikzpictures` instead of `\includegraphics` or to write external `\tikzpictures` and insert them with `\input`?

**Comment by BartoszMilewski** [comment]
Igal, what do you think?

**Comment by platipo** [comment]
Using the `\input` seems more organized to me, but since all the chapters are included with `\subfile` relative imports don't work indeed you have to type `\input{content/N.M/images/image.tizk}` in file `content/N.M/chapter.tex`.

So I'll insert the `\tikzpictures` directly into chapters.

**Comment by platipo** [comment]
The work has started, but just to see if we all agree I made a list of all possible images to redraw:
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/1.10/images/10_horizontal.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/1.10/images/2_natcomp.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/1.10/images/3_naturality.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/1.10/images/4_transport.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/1.10/images/5_vertical.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/1.10/images/6a_vertical.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/1.10/images/6_verticalnaturality.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/1.10/images/7_cathomset.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/1.10/images/8_cat-2-cat.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/1.10/images/9_horizontal.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/1.10/images/naturality.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/1.10/images/sideways.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/1.5/images/coproductpattern.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/1.5/images/not-a-product.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/1.5/images/productcandidates.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/1.5/images/uniqueness.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/1.7/images/functorcompos.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/1.7/images/functorid.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/1.7/images/functor.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/1.7/images/functormaybe.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/1.8/images/bifunctor.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/1.8/images/bimap.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/1.8/images/dimap.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/1.8/images/first.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/1.8/images/second.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/1.9/images/functionpattern.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/1.9/images/functionranking.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/1.9/images/universalfunctionobject.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/2.2/images/classes.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/2.2/images/colimit.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/2.2/images/conecommutativity.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/2.2/images/cone.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/2.2/images/conenaturality.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/2.2/images/continuity.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/2.2/images/coproductranking.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/2.2/images/equalizercone.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/2.2/images/equilizerlimit.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/2.2/images/homsetmapping.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/2.2/images/natmapping.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/2.2/images/productcone.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/2.2/images/productpattern.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/2.2/images/productranking.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/2.2/images/pullbackcone.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/2.2/images/pullbacklimit.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/2.2/images/twodelta.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/2.2/images/two.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/2.4/images/hom-functor.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/2.5/images/yoneda1.png
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/2.5/images/yoneda2.png
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/2.5/images/yoneda3.png
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/2.5/images/yoneda4.png
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/2.5/images/yoneda5.png
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/2.6/images/yoneda-embedding-2.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/2.6/images/yoneda-embedding.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/3.10/images/end-1.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/3.10/images/end1.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/3.10/images/end-21.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/3.10/images/end-2.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/3.10/images/end.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/3.11/images/kan10a.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/3.11/images/kan10b.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/3.11/images/kan112.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/3.11/images/kan12.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/3.11/images/kan13.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/3.11/images/kan14.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/3.11/images/kan15.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/3.11/images/kan2.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/3.11/images/kan31-e1492120512209.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/3.11/images/kan3-e1492120491591.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/3.11/images/kan5.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/3.11/images/kan6.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/3.11/images/kan7.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/3.11/images/kan81.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/3.11/images/kan92.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/3.12/images/composition.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/3.12/images/id.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/3.13/images/monomorphism.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/3.13/images/notmono.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/3.13/images/pullback.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/3.13/images/subsetinjection.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/3.13/images/true.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/3.14/images/lawvere1.png
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/3.14/images/liftpower.png
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/3.15/images/bicat.png
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/3.15/images/bimonad.png
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/3.15/images/compspan.png
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/3.15/images/monad.png
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/3.15/images/morphspan.png
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/3.15/images/pullspan.png
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/3.15/images/spanmonad.png
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/3.15/images/spanmul.png
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/3.15/images/span.png
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/3.15/images/spanunit.png
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/3.15/images/twocat.png
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/3.1/images/sheets.png
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/3.2/images/adj-1.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/3.2/images/adj-counit.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/3.2/images/adj-expo.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/3.2/images/adj-homsets.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/3.2/images/adj-productcat.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/3.2/images/adj-product.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/3.2/images/adj-unit.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/3.3/images/forgetful.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/3.3/images/forgettingmorphisms.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/3.3/images/freeimage.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/3.3/images/freemonadjunction.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/3.6/images/assoc1.png
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/3.6/images/assoc2.png
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/3.6/images/assocmon.png
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/3.6/images/assoc.png
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/3.6/images/assoctensor.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/3.6/images/exptree.png
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/3.6/images/horizcomp.png
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/3.6/images/unitlawcomp-1.png
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/3.6/images/unitlawcomp.png
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/3.6/images/unitmon.jpg
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/3.8/images/alg2.png
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/3.8/images/alg3a.png
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/3.8/images/alg3.png
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/3.8/images/alg4.png
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/3.8/images/alg5.png
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/3.8/images/alg6.png
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/3.8/images/alg7.png
 - https://github.com/hmemcpy/milewski-ctfp-pdf/blob/master/src/content/3.8/images/alg.png

**Comment by BartoszMilewski** [comment]
Some of these diagrams are just standard diagrams and can be redrawn. But a lot of them don't fit in the mold. The rule of thumb should be that the ones that look 3-dimensional, with shading and little clouds, should be left alone.

**Comment by platipo** [comment]
Thank you @BartoszMilewski!

I've opened a draft pull request with 17 diagrams and I'll upload others shortly.

**Comment by gosciufka** [comment]
![muv1262](https://user-images.githubusercontent.com/59889301/72372595-db7daf00-3706-11ea-9656-985c8a09428f.jpg) i think ITS ok
