### ISSUE TITLE
Any plans to add Kotlin snippets?

### ISSUE THREAD

**Issue by regmoraes** [hmemcpy/milewski-ctfp-pdf#220]
First of all, I'm currently reading the book and I'm really loving it! Second, despite don't having much difficult to undestand the code snippets in Scala, I think it would be cool if the code snippets was also available in Kotlin language, because even having support for functional programming, it's hard to find great Category Theory and Functional Programming contents written with it. So I think it would be great to have code snippets in Kotlin, to increase the number of programmers that would fell confortable with Categoy Theory by seeing content written in a language that is familiar for them.

**Comment by hmemcpy** [comment]
There's a massive effort happening to convert the book snippets to Kotlin, you can monitor the progress here: https://github.com/arrow-kt/Category-Theory-for-Programmers.kt
Once it's done, it's entirely possible that we'll merge it here and have a Kotlin edition.
