### ISSUE TITLE
Typo in Lawvere Theories diagram for Monads as Conends

### ISSUE THREAD

**Issue by steve-e** [hmemcpy/milewski-ctfp-pdf#227]
Hi,
I found one minor error in a diagram on page 358 of the scala pdf. I double checked it against the original diagram in the [Lawvere Theories](https://bartoszmilewski.com/2017/08/26/lawvere-theories/)

https://github.com/hmemcpy/milewski-ctfp-pdf/pull/226

Please check by eye 

Also, thanks for providing this great resource!

**Comment by hmemcpy** [comment]
Thank you. Merged.
