### ISSUE TITLE
OCaml version missing images and text runs off the page

### ISSUE THREAD

**Issue by ddickstein** [hmemcpy/milewski-ctfp-pdf#232]
This issue really pertains to [Arulselvan Madhavan's fork](https://github.com/ArulselvanMadhavan/milewski-ctfp-pdf/tree/ocaml) but issues aren't enabled for the fork so I'm adding it here.

I'm following #201 and saw that the final chapters were in, so I went ahead to try building it and seeing how it turned out. After addressing the various dependency complaints by `make ocaml` I was able to generate two pdfs that had the OCaml code snippets, but images were missing and the snippets often were cut off.

Are there some dependencies I'm missing that's causing this behavior?

I've checked out the OCaml branch of the fork at commit 56c552e1fb18be3fdaf7975b8b250dee89048644. The generated output version is v1.2.1-52-g56c552e.

---
### Cut off text
![cut-off-text](https://user-images.githubusercontent.com/802511/73237054-6b3d4780-4162-11ea-862e-d3c453a084e3.png)

### Missing image
![missing-image](https://user-images.githubusercontent.com/802511/73237055-6b3d4780-4162-11ea-9aae-ccca2284b22b.png)

**Comment by mseri** [comment]
For the first one, I think it did came out early on in my reviews as well. Ideally we should have the code be auto formatted by ocamlformat, although I don’t know how much we can automate it in the current structure of things. It may be that it is going to be all manual work :-/

**Comment by hmemcpy** [comment]
Yeah, sorry about that... I ended up manually formatting all files for the Scala edition :(

**Comment by hmemcpy** [comment]
I'm not sure why some images are missing, will take a look...

**Comment by ArulselvanMadhavan** [comment]
@ddickstein I have run the formatter and enabled issues in my fork

**Comment by hmemcpy** [comment]
Gah. I figured out why the images were missing... a long story short, a recent TexLive update fixed an issue with paths containing spaces, and another package was interfering with that (`\usepackage[multidot]{grffile}`). So I removed it, and now the images are working again. Images should be rendering now.
