### ISSUE TITLE
`make all` produces the same Haskell copy of the book for all three supported languages

### ISSUE THREAD

**Issue by toriningen** [hmemcpy/milewski-ctfp-pdf#245]
I'd assume that `make all` should produce three _different_ books - one for Haskell, one for Scala, and another one for OCaml. It seems that despite it produces three _differently named_ books, all of them contain Haskell snippets, which even made me wonder at first if OCaml is really that similar to Haskell that I can't tell any difference.

I suppose this is due to build artifacts from Haskell edition being reused while they shouldn't.

Similar issue arises if trying to compile any other language edition if something has been previously already built. So, compiling Scala after OCaml produces `category-theory-for-programmers-scala.pdf` with OCaml source, and so on.

**Comment by hmemcpy** [comment]
Hmm, I think this happened to me as well, but I remember fixing it... I'm currently on vacation, I'll take a look when I get back. Thanks for the report!
