### ISSUE TITLE
Since a couple of releases assets are uploaded twice - it's confusing

### ISSUE THREAD

**Issue by drupol** [hmemcpy/milewski-ctfp-pdf#255]
Hi,

Context:
* See the release: https://github.com/hmemcpy/milewski-ctfp-pdf/releases/tag/1b53921
* See the latest release: https://github.com/hmemcpy/milewski-ctfp-pdf/releases/tag/8336698

It looks like assets are uploaded twice, with a different name.

We need to investigate and try to clean this up in order to not confuse people.

**Comment by hmemcpy** [comment]
Hmm, you're right, it might be because Travis came back to life. I vaguely recall setting up pushing releases from there too. I think I'll just retire Travis CI for now...

**Comment by drupol** [comment]
> Hmm, you're right, it might be because Travis came back to life. I vaguely recall setting up pushing releases from there too. I think I'll just retire Travis CI for now...

Ooh indeed, it might probably be that thing indeed :)
