### ISSUE TITLE
Possibly a mistake that causes confusion

### ISSUE THREAD

**Issue by NariyasuHeseri** [hmemcpy/milewski-ctfp-pdf#285]
![Screenshot_20220225-013554](https://user-images.githubusercontent.com/31871512/155567566-66a92bd7-5de9-4367-ae1f-6cea6870c4f8.png)

On page 349 (see the screenshot),
shouldn't `Store f :: s -> Store f s` be  `Store f :: s -> Store (s -> a) s`?
The expression on the right-hand side of `::` is a type and apparently `f` is a value with type `s -> a`.

**Comment by BartoszMilewski** [comment]
The notation might be a bit confusing. What it says is that the type of the two expressions is the same. And a lambda would make it clrearer:

Store f ~ \s -> Store f s

**Comment by NariyasuHeseri** [comment]
> The notation might be a bit confusing. What it says is that the type of the two expressions is the same. And a lambda would make it clrearer:
> 
> Store f ~ \s -> Store f s

Thanks!
