### ISSUE TITLE
`make scala` fails to produce full PDF

### ISSUE THREAD

**Issue by mlliarm** [hmemcpy/milewski-ctfp-pdf#288]
Hello,

I tried building the source on my machine [1], but it's failing with errors. As a result only 5-6 pages are getting printed into PDF.

Please find the build log attached as [2] and the produced PDF as [3].

Any pointers or workarounds would be very welcome.

I'll keep googling to see if I can fix this, and if so I'll post the solution here.

Best regards,
Mike

---
[1]
```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic
```
[2]
[make_scala.log](https://github.com/hmemcpy/milewski-ctfp-pdf/files/8404092/make_scala.log)

[3]
[category-theory-for-programmers-scala.pdf](https://github.com/hmemcpy/milewski-ctfp-pdf/files/8404093/category-theory-for-programmers-scala.pdf)

**Comment by drupol** [comment]
Hello,

Are you using Nix?

**Comment by mlliarm** [comment]
Hi, 

Thanks for the reply.

Just installed Nix, and I'm getting a different error now when running `nix-shell` as per instructions:

```
milia@Newton:~/Documents/dev/latex/milewski-ctfp-pdf$ pwd
/home/milia/Documents/dev/latex/milewski-ctfp-pdf
milia@Newton:~/Documents/dev/latex/milewski-ctfp-pdf$ nix-shell
error: attribute 'flake-compat' missing

       at /home/milia/Documents/dev/latex/milewski-ctfp-pdf/shell.nix:5:65:

            4|     fetchTarball {
            5|       url = "https://github.com/edolstra/flake-compat/archive/${lock.nodes.flake-compat.locked.rev}.tar.gz";
             |                                                                 ^
            6|       sha256 = lock.nodes.flake-compat.locked.narHash;
(use '--show-trace' to show detailed location information)
```

:|

Installed Nix with `sh <(curl -L https://nixos.org/nix/install) --daemon` as suggested at the [Nix installation site](https://nixos.org/download.html).

Thanks for the fast response !

**Comment by mlliarm** [comment]
Full trace:

```bash
(ctfp-scala) milia@Newton:~/Documents/dev/latex/milewski-ctfp-pdf$ nix-shell --show-trace
error: attribute 'flake-compat' missing

       at /home/milia/Documents/dev/latex/milewski-ctfp-pdf/shell.nix:5:65:

            4|     fetchTarball {
            5|       url = "https://github.com/edolstra/flake-compat/archive/${lock.nodes.flake-compat.locked.rev}.tar.gz";
             |                                                                 ^
            6|       sha256 = lock.nodes.flake-compat.locked.narHash;

       … while realising the context of a path

       at /home/milia/Documents/dev/latex/milewski-ctfp-pdf/shell.nix:1:2:

            1| (import
             |  ^
            2|   (
```

Thx !

**Comment by drupol** [comment]
Tips:
1. Do `nix flake show` to print all the available editions
2. Do `nix build .#<edition>` to build the edition you want.

In you case, it will be: `nix build .#ctfp-scala`

**Comment by drupol** [comment]
You might need to enable support of flakes, which might not be enabled by default !

**Comment by mlliarm** [comment]
I might be doing something wrong:

```bash
(ctfp-scala) milia@Newton:~/Documents/dev/latex/milewski-ctfp-pdf$ nix build .#ctfp-scala
error: experimental Nix feature 'nix-command' is disabled; use '--extra-experimental-features nix-command' to override
(ctfp-scala) milia@Newton:~/Documents/dev/latex/milewski-ctfp-pdf$ nix flake show
error: experimental Nix feature 'nix-command' is disabled; use '--extra-experimental-features nix-command' to override
(ctfp-scala) milia@Newton:~/Documents/dev/latex/milewski-ctfp-pdf$ nix build .#ctfp-scala --extra-experimental-features nix-build
warning: unknown experimental feature 'nix-build'
error: experimental Nix feature 'nix-command' is disabled; use '--extra-experimental-features nix-command' to override
(ctfp-scala) milia@Newton:~/Documents/dev/latex/milewski-ctfp-pdf$ nix build .#ctfp-scala --extra-experimental-features nix-command
error: experimental Nix feature 'flakes' is disabled; use '--extra-experimental-features flakes' to override
```

**Comment by drupol** [comment]
No, you just need to enable Nix flakes :), see: 

![image](https://user-images.githubusercontent.com/252042/161420272-cb5655f8-237e-4d2f-9885-c4d519a51037.png)

**Comment by mlliarm** [comment]
Thank you very much !

Your suggestion at the previous comment fixed the `nix build .#ctfp-scala` issue, and now I can see packages getting downloaded.

I'll update this comment once the PDF is built !

It'd be nice & perhaps useful if you could add those steps on the README.md file for future users that encounter the same issue when using Nix to build the book :)

Thanks ! <3

**Comment by drupol** [comment]
Indeed, this is something to do ! I will try to focus on this soon !

**Comment by mlliarm** [comment]
@drupol if you'd like I can write up the missing steps on the README.md and send a PR :)

**Comment by drupol** [comment]
That would be truly amazing :) thanks !!!

**Comment by drupol** [comment]
Closing the issue, feel free to reopen if needed.
