### ISSUE TITLE
Result folder appears empty

### ISSUE THREAD

**Issue by behoppe** [hmemcpy/milewski-ctfp-pdf#312]
Hi, I installed Nix, cloned this repo, and built the 'ctfp' edition. It looked like it was working, but then it seemed that my result was empty. Eventually I discovered a hidden file `.pdf`, and renamed that. Voila! That hidden `.pdf` was the book, which I am now reading.

**Comment by drupol** [comment]
Hello,

I will immediately fix the issue if you could provide the commands to reproduce the issue.

Thanks!

**Comment by behoppe** [comment]
Hi @drupol and thank you. Below is a transcript of my session, including user errors, which starts after I installed nix, logged out, and logged back in. (So the first command is where I discover that nix is finally working.) Now that I have the book PDF, I don't expect to need nix again, but I'm happy if this helps prevent others from having the same problem.

~$ nix
error: no subcommand specified
~$ git clone https://github.com/hmemcpy/milewski-ctfp-pdf.git
Cloning into 'milewski-ctfp-pdf'...
remote: Enumerating objects: 6846, done.
remote: Counting objects: 100% (375/375), done.
remote: Compressing objects: 100% (247/247), done.
remote: Total 6846 (delta 157), reused 281 (delta 113), pack-reused 6471
Receiving objects: 100% (6846/6846), 71.19 MiB | 15.34 MiB/s, done.
Resolving deltas: 100% (2174/2174), done.
~$ cd milewski-ctfp-pdf/
~/milewski-ctfp-pdf$ nix flake show
error: experimental Nix feature 'nix-command' is disabled; use '--extra-experimental-features nix-command' to override
~/milewski-ctfp-pdf$ nix --experimental-features 'nix-command flakes' flake show 
git+file:///home/bruce/milewski-ctfp-pdf?ref=refs%2fheads%2fmaster&rev=32743b2738011a663ac69e0d70fd9f3ff08bdfc8
├───apps
│   ├───aarch64-darwin
│   ├───aarch64-linux
│   ├───x86_64-darwin
│   └───x86_64-linux
├───checks
│   ├───aarch64-darwin
│   ├───aarch64-linux
│   ├───x86_64-darwin
│   └───x86_64-linux
├───devShells
│   ├───aarch64-darwin
│   │   └───default: development environment 'nix-shell'
│   ├───aarch64-linux
│   │   └───default: development environment 'nix-shell'
│   ├───x86_64-darwin
│   │   └───default: development environment 'nix-shell'
│   └───x86_64-linux
│       └───default: development environment 'nix-shell'
├───formatter
│   ├───aarch64-darwin: package 'alejandra-3.0.0'
│   ├───aarch64-linux: package 'alejandra-3.0.0'
│   ├───x86_64-darwin: package 'alejandra-3.0.0'
│   └───x86_64-linux: package 'alejandra-3.0.0'
├───legacyPackages
│   ├───aarch64-darwin omitted (use '--legacy' to show)
│   ├───aarch64-linux omitted (use '--legacy' to show)
│   ├───x86_64-darwin omitted (use '--legacy' to show)
│   └───x86_64-linux omitted (use '--legacy' to show)
├───nixosConfigurations
├───nixosModules
├───overlays
└───packages
    ├───aarch64-darwin
    │   ├───ctfp: package 'ctfp-reader'
    │   ├───ctfp-ocaml: package 'ctfp-reader-ocaml'
    │   ├───ctfp-print: package 'ctfp-print'
    │   ├───ctfp-print-ocaml: package 'ctfp-print-ocaml'
    │   ├───ctfp-print-reason: package 'ctfp-print-reason'
    │   ├───ctfp-print-scala: package 'ctfp-print-scala'
    │   ├───ctfp-reason: package 'ctfp-reader-reason'
    │   └───ctfp-scala: package 'ctfp-reader-scala'
    ├───aarch64-linux
    │   ├───ctfp: package 'ctfp-reader'
    │   ├───ctfp-ocaml: package 'ctfp-reader-ocaml'
    │   ├───ctfp-print: package 'ctfp-print'
    │   ├───ctfp-print-ocaml: package 'ctfp-print-ocaml'
    │   ├───ctfp-print-reason: package 'ctfp-print-reason'
    │   ├───ctfp-print-scala: package 'ctfp-print-scala'
    │   ├───ctfp-reason: package 'ctfp-reader-reason'
    │   └───ctfp-scala: package 'ctfp-reader-scala'
    ├───x86_64-darwin
    │   ├───ctfp: package 'ctfp-reader'
    │   ├───ctfp-ocaml: package 'ctfp-reader-ocaml'
    │   ├───ctfp-print: package 'ctfp-print'
    │   ├───ctfp-print-ocaml: package 'ctfp-print-ocaml'
    │   ├───ctfp-print-reason: package 'ctfp-print-reason'
    │   ├───ctfp-print-scala: package 'ctfp-print-scala'
    │   ├───ctfp-reason: package 'ctfp-reader-reason'
    │   └───ctfp-scala: package 'ctfp-reader-scala'
    └───x86_64-linux
        ├───ctfp: package 'ctfp-reader'
        ├───ctfp-ocaml: package 'ctfp-reader-ocaml'
        ├───ctfp-print: package 'ctfp-print'
        ├───ctfp-print-ocaml: package 'ctfp-print-ocaml'
        ├───ctfp-print-reason: package 'ctfp-print-reason'
        ├───ctfp-print-scala: package 'ctfp-print-scala'
        ├───ctfp-reason: package 'ctfp-reader-reason'
        └───ctfp-scala: package 'ctfp-reader-scala'
~/milewski-ctfp-pdf$ nix build
error: experimental Nix feature 'nix-command' is disabled; use '--extra-experimental-features nix-command' to override
~/milewski-ctfp-pdf$ nix --experimental-features 'nix-command flakes' build
error: flake 'git+file:///home/bruce/milewski-ctfp-pdf' does not provide attribute 'packages.x86_64-linux.default' or 'defaultPackage.x86_64-linux'
~/milewski-ctfp-pdf$ nix --experimental-features 'nix-command flakes' build .#ctfp-reader
error: flake 'git+file:///home/bruce/milewski-ctfp-pdf' does not provide attribute 'packages.x86_64-linux.ctfp-reader', 'legacyPackages.x86_64-linux.ctfp-reader' or 'ctfp-reader'
~/milewski-ctfp-pdf$ nix --experimental-features 'nix-command flakes' build .#ctfp
~/milewski-ctfp-pdf$ ls
errata-1.0.0.md  errata-1.3.0.md  errata-scala.md  flake.lock  flake.nix  LICENSE  Makefile  README.md  result  src
~/milewski-ctfp-pdf$ cd result
~/milewski-ctfp-pdf/result$ ls
~/milewski-ctfp-pdf/result$ ls -a
.  ..  .pdf

**Comment by drupol** [comment]
Thanks will work on a fix tomorrow !

**Comment by drupol** [comment]
Issue has been fixed and merged, re-open the issue if this is not the case.

Have a good day.
