### ISSUE TITLE
A mistake in Section 6.3

### ISSUE THREAD

**Issue by daleydeng** [hmemcpy/milewski-ctfp-pdf#316]
![image](https://github.com/hmemcpy/milewski-ctfp-pdf/assets/770506/26534c7c-8291-4e98-9389-09365da05408)
this should be this
![image](https://github.com/hmemcpy/milewski-ctfp-pdf/assets/770506/f3087c45-804f-4c40-8307-2cb49d8a8c82)

from original blog
https://bartoszmilewski.com/2015/01/13/simple-algebraic-data-types/

Because, `Either` is not data constructor which needed in `data` decalration

**Comment by drupol** [comment]
Nice catch, could you submit a PR to fix it ?

**Comment by daleydeng** [comment]
seemed to be merged

**Comment by daleydeng** [comment]
seem already merged

**Comment by drupol** [comment]
It's merged in your fork. Could you submit the PR against this project?

**Comment by hmemcpy** [comment]
I saw @BartoszMilewski merge this (or, a similar fix https://github.com/hmemcpy/milewski-ctfp-pdf/pull/315) not too long ago. Are we sure this is still current? Or is it another place in the book?
