### ISSUE TITLE
latest pdf for category-theory-for-programmers-scala

### ISSUE THREAD

**Issue by Dieken** [hmemcpy/milewski-ctfp-pdf#329]
[category-theory-for-programmers-scala-print-2024.pdf](https://github.com/hmemcpy/milewski-ctfp-pdf/files/14458315/category-theory-for-programmers-scala-print-2024.pdf)

[category-theory-for-programmers-scala-2024.pdf](https://github.com/hmemcpy/milewski-ctfp-pdf/files/14458316/category-theory-for-programmers-scala-2024.pdf)

Compiled on 2024-03-01 for commit ab180d9 by Phoenix-Wood.

**Comment by drupol** [comment]
?

**Comment by Dieken** [comment]
It's just for your convenience to get the latest version.

**Comment by Tasselmi** [comment]
For the [category-theory-for-programmers-scala-print-2024.pdf](https://github.com/hmemcpy/milewski-ctfp-pdf/files/14458315/category-theory-for-programmers-scala-print-2024.pdf) version, it seems that the text on every other page of this book is misaligned.

**Comment by drupol** [comment]
Could you please show us with a screenshot and indicate the page number?

**Comment by drupol** [comment]
@Tasselmi ^^

**Comment by dabrowski-adam** [comment]
> For the [category-theory-for-programmers-scala-print-2024.pdf](https://github.com/hmemcpy/milewski-ctfp-pdf/files/14458315/category-theory-for-programmers-scala-print-2024.pdf) version, it seems that the text on every other page of this book is misaligned.

The print version needs to accommodate the binding to the spine, so the inside margins are larger. That's why even and odd pages look differently.
