### ISSUE TITLE
Possible typo in 3.5

### ISSUE THREAD

**Issue by ktgw0316** [hmemcpy/milewski-ctfp-pdf#337]
https://github.com/hmemcpy/milewski-ctfp-pdf/blob/c46c3669d4cd43d750c26525e379ded66d4eda7d/src/content/3.5/monads-and-effects.tex#L389-L390

I think this "as a functor" is a typo for "as a container". Am I correct?

**Comment by drupol** [comment]
To my understanding, a monad is, to some extent, a container. Therefore, I don't think this is invalid.

I'll let @BartoszMilewski answer this.

**Comment by BartoszMilewski** [comment]
The idea is to see functors as containers of stuff.

**Comment by ktgw0316** [comment]
Thank you for the clarification.
