### ISSUE TITLE
Question: Difference between "arrow" and "morphism"

### ISSUE THREAD

**Issue by ktgw0316** [hmemcpy/milewski-ctfp-pdf#342]
This may be a silly question, but what is the difference between the terms "arrow" and "morphism"?

I understand that they refer to the same thing, but I don't understand how the terms are used differently.
For example, why is "Kleisli arrow" used instead of "Kleisli morphism" in this book?

**Comment by BartoszMilewski** [comment]
They are interchangeable. You can say Kleisli morphism. I personally prefer to use the term "arrow", but I want the readers to be familiar with "morphism," which they will find used in the literature.
