### ISSUE TITLE
Cover picture

### ISSUE THREAD

**Issue by hmemcpy** [hmemcpy/milewski-ctfp-pdf#37]
Perhaps @BartoszMilewski could provide one?

**Comment by aminb** [comment]
I noticed there are two issues with the coverpage:

- the path to `commutative_diagram.png` is a hard-coded absolute path in `coverpage.svg`, and
- the cover page fonts aren't properly rendered in the pdf (the "Category Theory for Programmers" should've been typeset in Alegreya but it's not).

**Comment by hmemcpy** [comment]
Yikes! Thanks for the heads up! I guess "it worked on my machine", so I hadn't noticed. I used an image from wikipedia, but I want to replace it eventually with a **worthy** cover image!

I'll try to fix the path and missing font!

**Comment by aminb** [comment]
Cheers! Thanks for your effort of turning CTFP into a pdf.
