### ISSUE TITLE
Period missing

### ISSUE THREAD

**Issue by rrohbeck** [hmemcpy/milewski-ctfp-pdf#47]
> tures invading imperative languages. Even Java, the bastion of object-
> oriented programming, let the lambdas in C++ has recently been evolv-

**Comment by DevJac** [comment]
Agreed, there should be a period after "let the lambdas in".

**Comment by Blaisorblade** [comment]
Disagree with @hmemcpy's fix, @DevJac's makes more sense.

**Comment by hmemcpy** [comment]
Yeah, I've misread the original sentence... will fix.
