### ISSUE TITLE
Correctly set up subfiles

### ISSUE THREAD

**Issue by hmemcpy** [hmemcpy/milewski-ctfp-pdf#48]
See https://www.sharelatex.com/learn/Multi-file_LaTeX_projects

This might help with pandoc/epub conversions (#46)

**Comment by Blaisorblade** [comment]
FWIW, just keeping chapters in separate files doesn't require `subfile`.

Apparently, that package lets you compile chapters independently* — which is pretty cool (normally one has to resort to `\include` and `\includeonly`, which works but is pretty annoying). So if you don't use that feature, maybe dropping `subfile` is an (inconvenient) solution. (I suspect conditional compilation with the `comment` package might help disabling `subfile` when annoying, but this can be tricky—and pandoc wouldn't get it either).

From `subfile` docs (which I find on TeXLive through `texdoc subfiles`, recommended or on CTAN at http://ctan.mirror.garr.it/mirrors/CTAN/macros/latex/contrib/subfiles/subfiles.pdf):

> With the subfiles set, the typesetting of a multi-file project consisting of one main file and one or more subsidiary files (subfiles) is more comfortable, since the user can LATEX either the main file, which will \input the subfiles normally, or the subfiles by themselves, which take the preamble of the main file and become self-sufficient LATEX documents.

**Comment by Blaisorblade** [comment]
(BTW checking it out, didn't know about it and would have been useful!)

**Comment by hmemcpy** [comment]
I initially went with subfiles because I didn't want to put everything in one giant .tex file (to allow working on individual chapters separately). In addition, I had to add this:

https://github.com/hmemcpy/milewski-ctfp-pdf/blob/a3a74e06e96fa6ea4834f0e4cebb7877629542db/src/preamble.tex#L94-L103

so that the images could be embedded using relative path.

**Comment by Blaisorblade** [comment]
> I initially went with subfiles because I didn't want to put everything in one giant .tex file (to allow working on individual chapters separately).

To rephrase: if you want just that, the main file just needs to use `\input{chapter1}`, without `subfile`, and `\input` just inlines the content of `chapter1.tex`.

**Comment by hmemcpy** [comment]
Closing this for now. The way I have it set up lets me include relative images, and I don't want to spend anymore time on this.
