### ISSUE TITLE
Broken external link

### ISSUE THREAD

**Issue by ygale** [hmemcpy/milewski-ctfp-pdf#50]
In chapter 11 "Declarative Programming", there is a link to "Tatsuya Hagino’s thesis". This link is broken. Furthermore, this should really be a bibliographic reference, not just an external link. I suspect that there are other examples of both of those problems scattered throughout the book.

The link URL is:

`http://synrc.com/publications/cat/Category%20Theory/Type%20Theory/Hagino%20T.%20A%20Categorical%20Programming%20Language.pdf`

**Comment by hmemcpy** [comment]
Hmm, that does indeed seem to be broken, the URL is 404 (also in the original blogpost).
I found this paper with the same title: http://web.sfc.keio.ac.jp/~hagino/thesis.pdf
Can someone confirm it's the same one? @BartoszMilewski

**Comment by BartoszMilewski** [comment]
Yes, that's the paper. I'll fix the link in the blog.

**Comment by hmemcpy** [comment]
Awesome! I'll replace it in the book :)
