### ISSUE TITLE
Set up PDF build in Travis CI

### ISSUE THREAD

**Issue by hmemcpy** [hmemcpy/milewski-ctfp-pdf#58]
https://harshjv.github.io/blog/setup-latex-pdf-build-using-travis-ci/

Make sure all the prerequisites (e.g., fonts) are installed

**Comment by q10** [comment]
+1

**Comment by marulitua** [comment]
I'll try to do it

**Comment by marulitua** [comment]
@hmemcpy I think, we can close this issue
