### ISSUE TITLE
Listings?

### ISSUE THREAD

**Issue by xcthulhu** [hmemcpy/milewski-ctfp-pdf#67]
Rather than use `Verbatim` environments, perhaps consider using the `listings` package: 

https://en.wikibooks.org/wiki/LaTeX/Source_Code_Listings

**Comment by hmemcpy** [comment]
Yeah, it's the plan (but I found [minted](https://ctan.org/pkg/minted) slightly better for my needs - it supports math escape modes).
It was automatically converted to `verbatim` when I converted html -> latex with pandoc, so I left it alone.

I'll handle source code at a later time, there's a lot of pseudo-haskell in there that doesn't highlight properly.

**Comment by hmemcpy** [comment]
Closing in favor of (planned) work on #71
