### ISSUE TITLE
Confusing Wording

### ISSUE THREAD

**Issue by xcthulhu** [hmemcpy/milewski-ctfp-pdf#68]
On page xvi of the introduction, there is the following oddly phrased sentence:

>  Even Java, the bastion of object oriented programming, let the lambdas in C++ has recently been evolving at a frantic pace — a new standard every few years — trying to catch up with the changing world.

I can make a PR with a suggested edit if you would like.

**Comment by hmemcpy** [comment]
Thank you, but it was already fixed by #55. The PDF is slightly out of date, lots of small fixes have been made in the source. A new version should be published soon.
In the meantime, if you find a typo, feel free to send a PR directly! :)

**Comment by hmemcpy** [comment]
(p.s. I might have misread your question. It's probably best not to change the original text too much, Bartosz [said](https://twitter.com/BartoszMilewski/status/914180127214362624) that he'd like to proofread this book first. So if it ever makes it to an actual editor, then I'm sure we can tweak the language :))
