### ISSUE TITLE
3.12 - "Enriched Categories" - consider replacing hand-drawn equations with TeX

### ISSUE THREAD

**Issue by hmemcpy** [hmemcpy/milewski-ctfp-pdf#75]
These could be replaced with TeX equations and arrows, e.g.:

![image](https://user-images.githubusercontent.com/601206/31582550-62bfad92-b18f-11e7-82c5-ef2ff0434bee.png)

**Comment by mseri** [comment]
My memories of commutative diagrams in latex are painful, it looks like this could greatly reduce the pain: https://github.com/yishn/tikzcd-editor

**Comment by ShrykeWindgrace** [comment]
I can do that, these diagrams do not seem to be complicated.

**Comment by hmemcpy** [comment]
That would be amazing, thanks! :)

**Comment by hmemcpy** [comment]
Fixed in #99!
