### ISSUE TITLE
Build fails because src/coverpage.pdf is missing

### ISSUE THREAD

**Issue by gbabin** [hmemcpy/milewski-ctfp-pdf#81]
The file `src/coverpage.pdf` is missing and is not generated since commit b8f180034a1f49a79979ae6c61b4000253e83014 where `src/coverpage.svg` was removed and `Makefile` modified.
The file is ignored due to `src/.gitignore`.

**Comment by hmemcpy** [comment]
Whoops! 👀 
You're right, sorry about that!
