### ISSUE TITLE
"Andrew Su on"

### ISSUE THREAD

**Issue by gfixler** [hmemcpy/milewski-ctfp-pdf#82]
In the Acknowledgements, the following line appears:

"I’d like to thank Andrew Su on for rewriting my C++ monoid concept code according to his and Bjarne Stroustrup’s latest proposal."

I can't find an Andrew Su linked with Bjarne Stroupstrup online (didn't search very hard). I'm wondering if the name is "Su_on", with the middle part of the name missing, or if the "on" is just a typo.

**Comment by hmemcpy** [comment]
Great catch! It's "Sutton", turns out! I wonder what happened to the `tt` (eaten by a bad ligature?)
The original acknowledgment is here: https://bartoszmilewski.com/2014/12/23/kleisli-categories/

I'll fix it, thank you!
