### ISSUE TITLE
Newest release is blank

### ISSUE THREAD

**Issue by sampollard** [hmemcpy/milewski-ctfp-pdf#87]
The title pretty much says it all. v0.4 is 496 blank pages.

**Comment by fosskers** [comment]
Mine's not?

**Comment by sampollard** [comment]
Weird. It seems to be blank only on Mac Preview. I tested it with Adobe Reader and on mobile and both work. It must be an issue with Preview.

**Comment by hmemcpy** [comment]
Very odd, another reader reported garbled pages. I re-uploaded the PDF, downloaded it again to check it was fine. Please redownload and let me know! Thanks!

**Comment by sampollard** [comment]
I redownloaded and it works on Preview. Thanks for the response!
