### ISSUE TITLE
Demons have taken over pages 126-286

### ISSUE THREAD

**Issue by gfixler** [hmemcpy/milewski-ctfp-pdf#89]
Here's page 126 as viewed in Chrome on Linux. The next 160 pages look pretty much like that. Viewing in Evince on Linux, this specific range of pages appears mostly blank, with occasional horizontal hairlines in various, wild positions.
![2017-11-11-042657_572x758_scrot](https://user-images.githubusercontent.com/1888391/32689448-a692d5de-c699-11e7-86f0-b4088cfc3748.png)

**Comment by hmemcpy** [comment]
Ouch! That's a second report of missing/screwed up pages... Let me see what's up!

**Comment by hmemcpy** [comment]
I just built and reuploaded the PDF. Downloaded it again - seems fine. Maybe something got screwed up in the previous upload. Possibly explains what happened to #87 as well.
Please let me know if I exorcised the demons?

**Comment by fosskers** [comment]
I grabbed the most recent version again and don't see any demons... I think you squashed them :imp:

**Comment by hmemcpy** [comment]
Amaze! Closing then :)

**Comment by gfixler** [comment]
Yep, demons appear thwarted, thanks!
