### ISSUE TITLE
PDF can't be viewed in MacOS

### ISSUE THREAD

**Issue by Qiyamah** [hmemcpy/milewski-ctfp-pdf#90]
Topic says it all.
The pages are blank...

**Comment by hmemcpy** [comment]
Please download it again, I reuploaded another version earlier. Let me know if it's still blank.

**Comment by Qiyamah** [comment]
Pages are visible, but the page preview is still blank... 
Thanks , at least i can print it out now.

**Comment by maarek** [comment]
It's working for me now.
