### ISSUE TITLE
Typo in section 10.4

### ISSUE THREAD

**Issue by Dalzhim** [hmemcpy/milewski-ctfp-pdf#91]
I believe there is a typo in section 10.4 2-Categories. The sentence "In fact they are members of two different functor categories:" is followed by categories `D^E` and `E^D`. I believe the intent was `D^C` and `E^D` as we are talking about the morphisms on morphisms α and β, with :
```
α :: F → F′
β :: G → G′
F :: C → D
G :: D → E```

**Comment by hmemcpy** [comment]
Fixed via #92
