### ISSUE TITLE
Should be mentioned this option in the README

### ISSUE THREAD

**Issue by jonaprieto** [hmemcpy/milewski-ctfp-pdf#96]
Randomly I found this in Lulu:

http://www.lulu.com/shop/bartosz-milewski/category-theory-for-programmers/hardcover/product-23389988.html

the version there is clearly outdated (v0.3 October 2017).

I think in the README should be some mention of this option to get a
copy since some guys like prefer read on paper rather than a PDF.

**Comment by mseri** [comment]
How can the version there be kept updated?

**Comment by hmemcpy** [comment]
The lulu link was set up by https://twitter.com/catamorphisms, it's not under mine (or Bartosz') control.
There was a bit of talk on twitter to have the ownership transferred, but it hadn't happened yet. Also, I'm not sure how to keep the book updated, but I'm sure lulu has an API.

I'll see if the ownership for the lulu account can be transferred. Once it's done, I'll add it to the README.

**Comment by BartoszMilewski** [comment]
Igal,
I wonder if you could just create your own account on lulu and put the book
there. We could ask catamorphism to remove his version (maybe even at the
same time).
--Bartosz

**Comment by zarelit** [comment]
I think this issue can be closed as it is resolved by https://github.com/hmemcpy/milewski-ctfp-pdf/commit/a16937caf78d69f033e6812e82dbbfa2cff45182

**Comment by hmemcpy** [comment]
Yep! Thanks!
